 *> setup the identification division
IDENTIFICATION DIVISION.
*> setup the program id
PROGRAM-ID. HELLO.
*> setup the procedure division (like 'main' function)
PROCEDURE DIVISION.
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
*> print a string
DISPLAY 'tr0ll'.
*> end our program
STOP RUN.